name: Update Portfolio

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v3

      - name: Fetch User's Repositories
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Fetching repositories..."
          curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/user/repos?per_page=100 | \
            jq -r '.[] | {name: .name, html_url: .html_url}' > repos.json

      - name: Fetch README Files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "# My GitHub Portfolio" > README.md
          echo "" >> README.md
          jq -c '.[] | {name: .name, html_url: .html_url}' repos.json | while read repo; do
            REPO_NAME=$(echo $repo | jq -r '.name')
            REPO_URL=$(echo $repo | jq -r '.html_url')
            README_URL="https://raw.githubusercontent.com/username/$REPO_NAME/main/README.md"
            
            echo "## [$REPO_NAME]($REPO_URL)" >> README.md
            echo "" >> README.md
            
            curl -s -H "Authorization: token $GH_TOKEN" $README_URL >> README.md || echo "README not found for $REPO_NAME" >> README.md
            echo "" >> README.md
            echo "---" >> README.md
            echo "" >> README.md
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Updated portfolio with latest repositories"
          git push
